name: Upload Software to TIRA
on: workflow_dispatch
jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install required python packages
        run: |
          python -m pip install --upgrade pip
          pip3 install tira
      - name: Build, test, and upload image
        run: |
          docker build -t registry.webis.de/code-research/tira/tira-user-ssnites/github-action-submission:0.0.1 -f ${{ github.workspace }}/Dockerfile ${{ github.workspace }}
          tira-run --tira-client-token ${{ secrets.TIRA_CLIENT_TOKEN }} --input-dataset ideology-and-power-identification-in-parliamentary-debates-2024/toy-dataset-20240424-training --image registry.webis.de/code-research/tira/tira-user-ssnites/github-action-submission:0.0.1 --push true --fail-if-output-is-empty
